USE [master]
GO

/****** Object:  Database [PaisesBD]    Script Date: 07/09/2020 14:43:53 ******/
DROP DATABASE [PaisesBD]
GO

/****** Object:  Database [PaisesBD]    Script Date: 07/09/2020 14:43:53 ******/
CREATE DATABASE [PaisesBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PaisesBD', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PaisesBD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PaisesBD_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PaisesBD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PaisesBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PaisesBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PaisesBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PaisesBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PaisesBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PaisesBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [PaisesBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PaisesBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PaisesBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PaisesBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PaisesBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PaisesBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PaisesBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PaisesBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PaisesBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PaisesBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PaisesBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PaisesBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PaisesBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PaisesBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PaisesBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PaisesBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PaisesBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PaisesBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PaisesBD] SET  MULTI_USER 
GO

ALTER DATABASE [PaisesBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PaisesBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PaisesBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PaisesBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PaisesBD] SET  READ_WRITE 
GO


USE [PaisesBD]
GO

/****** Object:  Table [dbo].[tCountryInfo]    Script Date: 07/09/2020 14:44:05 ******/
DROP TABLE [dbo].[tCountryInfo]
GO

/****** Object:  Table [dbo].[tCountryInfo]    Script Date: 07/09/2020 14:44:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tCountryInfo](
	[IDPais] [nchar](2) NOT NULL,
	[sName] [nchar](30) NULL,
	[sCapitalCity] [nchar](30) NULL,
	[sPhoneCode] [int] NULL,
	[sContinentCode] [nchar](2) NULL,
	[sCurrencyISOCode] [nchar](3) NULL,
	[sCountryFlag] [nchar](100) NULL,
 CONSTRAINT [PK_tCountryInfo] PRIMARY KEY CLUSTERED 
(
	[IDPais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [PaisesBD]
GO

ALTER TABLE [dbo].[Languages] DROP CONSTRAINT [FKIDLingua]
GO

/****** Object:  Table [dbo].[Languages]    Script Date: 07/09/2020 14:44:28 ******/
DROP TABLE [dbo].[Languages]
GO

/****** Object:  Table [dbo].[Languages]    Script Date: 07/09/2020 14:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Languages](
	[IDLingua] [nchar](3) NOT NULL,
	[IDPais] [nchar](2) NOT NULL,
	[sName] [nchar](30) NULL,
 CONSTRAINT [PK_Languages] PRIMARY KEY CLUSTERED 
(
	[IDLingua] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Languages]  WITH CHECK ADD  CONSTRAINT [FKIDLingua] FOREIGN KEY([IDPais])
REFERENCES [dbo].[tCountryInfo] ([IDPais])
GO

ALTER TABLE [dbo].[Languages] CHECK CONSTRAINT [FKIDLingua]
GO


